volumes:
  nvm-cache:

services:
  backend:
    # https://github.com/microsoft/vscode-remote-release/issues/10215
    image: localhost/trustify-operator_devcontainer-backend:latest
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${CONTEXT_PATH}/Dockerfile
      args:
        USER_UID: ${USER_UID}
    privileged: true
    userns_mode: "keep-id"
    environment:
      TRUSTD_DB_HOST: db
      HTTP_SERVER_BIND_ADDR: "::"
    command: tail -f /dev/null
    volumes:
      - ${REPO_PATH}:/workspace:cached
      - nvm-cache:/home/vscode/.m2
      - /run/user/115091/podman/podman.sock:/var/run/docker-host.sock
