volumes:
  npm-cache:

services:
  exhort-javascript-api:
    image: localhost/exhort-javascript-api_devcontainer-exhort-javascript-api:latest
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${CONTEXT_PATH}/Dockerfile
      args:
        USER_UID: ${USER_UID}
    privileged: true
    userns_mode: "keep-id"
    command: tail -f /dev/null
    volumes:
      - ${REPO_PATH}:/workspace:cached
      - npm-cache:/home/vscode/.npm
