networks:
  trustify:

volumes:
  npm-cache:
  nvim-cache:

services:
  trustify-ui:
    image: localhost/trustify-ui_devcontainer-frontend:latest
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${CONTEXT_PATH}/Dockerfile
      args:
        USER_UID: ${USER_UID}
    privileged: true
    userns_mode: "keep-id"
    environment:
      TRUSTIFY_API_URL: http://trustify:8080
      OIDC_SERVER_URL: http://localhost:9090/realms/trustd
      OIDC_CLIENT_ID: ui
      PLAYWRIGHT_AUTH_URL: http://trustify-keycloak:8080/realms/trustd
    command: tail -f /dev/null
    volumes:
      - ${REPO_PATH}:/workspace:cached
      - npm-cache:/home/vscode/.npm
      - nvim-cache:/home/vscode/.local/share/nvim
      - ${NVIM_PATH}:/home/vscode/.config/nvim
    networks:
      - trustify
