receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  otlp:
    endpoint: trustify-demo-jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch: { }

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ debug ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlp ]
