worker_processes 1;
error_log /var/log/nginx/error.log;

events {
    worker_connections 1024;
    accept_mutex off;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    types_hash_max_size 4096;
    access_log /var/log/nginx/access.log;

    upstream pulp-content {
        server 127.0.0.1:24816;
    }

    upstream pulp-api {
        server 127.0.0.1:24817;
    }

    server {
        listen 80 default_server;
        server_name _;
        client_max_body_size 0;
        keepalive_timeout 5;

        # Upstream CI / pulpcore default content prefix.
        location /pulp/content/ {
            include /etc/nginx/pulp-proxy-params.conf;
            proxy_pass http://pulp-content;
        }

        location /pulp/ {
            include /etc/nginx/pulp-proxy-params.conf;
            proxy_pass http://pulp-api;
        }

        location /auth/login/ {
            include /etc/nginx/pulp-proxy-params.conf;
            proxy_pass http://pulp-api;
        }

        include /etc/nginx/pulp/*.conf;

        location / {
            include /etc/nginx/pulp-proxy-params.conf;
            proxy_pass http://pulp-api;
        }
    }
}
