networks:
  trustify:

volumes:
  npm-cache:

services:
  app:
    image: localhost/trustify-ui-tests_devcontainer-app:latest
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${CONTEXT_PATH}/Dockerfile
      args:
        USER_UID: ${USER_UID}
    privileged: true
    userns_mode: "keep-id"
    command: tail -f /dev/null
    volumes:
      - ${REPO_PATH}:/workspace:cached
      - npm-cache:/home/vscode/.npm
    networks:
      - trustify
