volumes:
  npm-cache:

services:
  trustification.github.io:
    image: localhost/trustification.github.io_devcontainer-app:latest
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${CONTEXT_PATH}/Dockerfile
      args:
        USER_UID: ${USER_UID}
    privileged: true
    userns_mode: "keep-id"
    command: tail -f /dev/null
    volumes:
      - ${REPO_PATH}:/workspace:cached
      - npm-cache:/home/vscode/.npm
